/// Enumeration of possible CD-TEXT languages.
/// 
/// The language code is encoded as specified in ANNEX 1 to part 5 of EBU
/// Tech 32 58 -E (1991).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub(super) enum Language {
    #[default]
    Unknown,
    Albanian,
    Breton,
    Catalan,
    Croatian,
    Welsh,
    Czech,
    Danish,
    German,
    English,
    Spanish,
    Esperanto,
    Estonian,
    Basque,
    Faroese,
    French,
    Frisian,
    Irish,
    Gaelic,
    Galician,
    Icelandic,
    Italian,
    Lappish,
    Latin,
    Latvian,
    Luxembourgian,
    Lithuanian,
    Hungarian,
    Maltese,
    Dutch,
    Norwegian,
    Occitan,
    Polish,
    Portuguese,
    Romanian,
    Romansh,
    Serbian,
    Slovak,
    Slovenian,
    Finnish,
    Swedish,
    Turkish,
    Flemish,
    Wallon,
    Zulu,
    Vietnamese,
    Uzbek,
    Urdu,
    Ukrainian,
    Thai,
    Telugu,
    Tatar,
    Tamil,
    Tadzhik,
    Swahili,
    Sranantongo,
    Somali,
    Sinhalese,
    Shona,
    SerboCroat,
    Russian,
    Quechua,
    Pushtu,
    Punjabi,
    Persian,
    Papamiento,
    Oriya,
    Nepali,
    Ndebele,
    Marathi,
    Moldavian,
    Malaysian,
    Malagasay,
    Macedonian,
    Laotian,
    Korean,
    Khmer,
    Kazakh,
    Kannada,
    Japanese,
    Indonesian,
    Hindi,
    Hebrew,
    Hausa,
    Gurani,
    Gujurati,
    Greek,
    Georgian,
    Fulani,
    Dari,
    Churash,
    Chinese,
    Burmese,
    Bulgarian,
    Bengali,
    Bielorussian,
    Bambora,
    Azerbaijani,
    Assamese,
    Armenian,
    Arabic,
    Amharic,
}

impl TryFrom<u8> for Language {
    type Error = u8;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0x00 => Ok(Language::Unknown),
            0x01 => Ok(Language::Albanian),
            0x02 => Ok(Language::Breton),
            0x03 => Ok(Language::Catalan),
            0x04 => Ok(Language::Croatian),
            0x05 => Ok(Language::Welsh),
            0x06 => Ok(Language::Czech),
            0x07 => Ok(Language::Danish),
            0x08 => Ok(Language::German),
            0x09 => Ok(Language::English),
            0x0A => Ok(Language::Spanish),
            0x0B => Ok(Language::Esperanto),
            0x0C => Ok(Language::Estonian),
            0x0D => Ok(Language::Basque),
            0x0E => Ok(Language::Faroese),
            0x0F => Ok(Language::French),
            0x10 => Ok(Language::Frisian),
            0x11 => Ok(Language::Irish),
            0x12 => Ok(Language::Gaelic),
            0x13 => Ok(Language::Galician),
            0x14 => Ok(Language::Icelandic),
            0x15 => Ok(Language::Italian),
            0x16 => Ok(Language::Lappish),
            0x17 => Ok(Language::Latin),
            0x18 => Ok(Language::Latvian),
            0x19 => Ok(Language::Luxembourgian),
            0x1A => Ok(Language::Lithuanian),
            0x1B => Ok(Language::Hungarian),
            0x1C => Ok(Language::Maltese),
            0x1D => Ok(Language::Dutch),
            0x1E => Ok(Language::Norwegian),
            0x1F => Ok(Language::Occitan),
            0x20 => Ok(Language::Polish),
            0x21 => Ok(Language::Portuguese),
            0x22 => Ok(Language::Romanian),
            0x23 => Ok(Language::Romansh),
            0x24 => Ok(Language::Serbian),
            0x25 => Ok(Language::Slovak),
            0x26 => Ok(Language::Slovenian),
            0x27 => Ok(Language::Finnish),
            0x28 => Ok(Language::Swedish),
            0x29 => Ok(Language::Turkish),
            0x2A => Ok(Language::Flemish),
            0x2B => Ok(Language::Wallon),
            0x45 => Ok(Language::Zulu),
            0x46 => Ok(Language::Vietnamese),
            0x47 => Ok(Language::Uzbek),
            0x48 => Ok(Language::Urdu),
            0x49 => Ok(Language::Ukrainian),
            0x4A => Ok(Language::Thai),
            0x4B => Ok(Language::Telugu),
            0x4C => Ok(Language::Tatar),
            0x4D => Ok(Language::Tamil),
            0x4E => Ok(Language::Tadzhik),
            0x4F => Ok(Language::Swahili),
            0x50 => Ok(Language::Sranantongo),
            0x51 => Ok(Language::Somali),
            0x52 => Ok(Language::Sinhalese),
            0x53 => Ok(Language::Shona),
            0x54 => Ok(Language::SerboCroat),
            0x56 => Ok(Language::Russian),
            0x57 => Ok(Language::Quechua),
            0x58 => Ok(Language::Pushtu),
            0x59 => Ok(Language::Punjabi),
            0x5A => Ok(Language::Persian),
            0x5B => Ok(Language::Papamiento),
            0x5C => Ok(Language::Oriya),
            0x5D => Ok(Language::Nepali),
            0x5E => Ok(Language::Ndebele),
            0x5F => Ok(Language::Marathi),
            0x60 => Ok(Language::Moldavian),
            0x61 => Ok(Language::Malaysian),
            0x62 => Ok(Language::Malagasay),
            0x63 => Ok(Language::Macedonian),
            0x64 => Ok(Language::Laotian),
            0x65 => Ok(Language::Korean),
            0x66 => Ok(Language::Khmer),
            0x67 => Ok(Language::Kazakh),
            0x68 => Ok(Language::Kannada),
            0x69 => Ok(Language::Japanese),
            0x6A => Ok(Language::Indonesian),
            0x6B => Ok(Language::Hindi),
            0x6C => Ok(Language::Hebrew),
            0x6D => Ok(Language::Hausa),
            0x6E => Ok(Language::Gurani),
            0x6F => Ok(Language::Gujurati),
            0x70 => Ok(Language::Greek),
            0x71 => Ok(Language::Georgian),
            0x72 => Ok(Language::Fulani),
            0x73 => Ok(Language::Dari),
            0x74 => Ok(Language::Churash),
            0x75 => Ok(Language::Chinese),
            0x76 => Ok(Language::Burmese),
            0x77 => Ok(Language::Bulgarian),
            0x78 => Ok(Language::Bengali),
            0x79 => Ok(Language::Bielorussian),
            0x7A => Ok(Language::Bambora),
            0x7B => Ok(Language::Azerbaijani),
            0x7C => Ok(Language::Assamese),
            0x7D => Ok(Language::Armenian),
            0x7E => Ok(Language::Arabic),
            0x7F => Ok(Language::Amharic),
            unmapped => Err(unmapped),
        }
    }
}
